### ISSUE TITLE
Crash report 1.14.4

### ISSUE THREAD

**Issue by XeonMations** [ReallySub/Weeping-Angels-Mod#116]
---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 7/11/20 12:36 AM
Description: Exception ticking world

java.lang.NoClassDefFoundError: me/swirtzly/minecraft/angels/client/models/poses/PoseManager
	at me.swirtzly.minecraft.angels.common.entities.WeepingAngelEntity.func_70088_a(WeepingAngelEntity.java:87) ~[?:2.1.6] {re:classloading}
	at net.minecraft.entity.Entity.<init>(Entity.java:219) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:fml:shetiphiancore:Entity.move,xf:fml:shetiphiancore:Entity.createRunningParticles,pl:mixin:A}
	at net.minecraft.entity.LivingEntity.<init>(LivingEntity.java:192) ~[?:?] {re:classloading,xf:fml:shetiphiancore:LivingEntity.fall,re:mixin}
	at net.minecraft.entity.MobEntity.<init>(MobEntity.java:99) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.entity.CreatureEntity.<init>(SourceFile:12) ~[?:?] {re:classloading}
	at net.minecraft.entity.monster.MonsterEntity.<init>(SourceFile:26) ~[?:?] {re:classloading}
	at me.swirtzly.minecraft.angels.common.entities.QuantumLockBaseEntity.<init>(QuantumLockBaseEntity.java:31) ~[?:2.1.6] {re:classloading}
	at me.swirtzly.minecraft.angels.common.entities.WeepingAngelEntity.<init>(WeepingAngelEntity.java:65) ~[?:2.1.6] {re:classloading}
	at me.swirtzly.minecraft.angels.common.entities.WeepingAngelEntity.<init>(WeepingAngelEntity.java:61) ~[?:2.1.6] {re:classloading}
	at me.swirtzly.minecraft.angels.common.WAObjects$EntityEntries$$Lambda$4423/1766344207.create(Unknown Source) ~[?:?] {}
	at net.minecraft.entity.EntityType.func_200721_a(EntityType.java:412) ~[?:?] {re:classloading}
	at net.minecraft.world.spawner.WorldEntitySpawner.func_222263_a(WorldEntitySpawner.java:113) ~[?:?] {re:classloading}
	at net.minecraft.world.server.ServerChunkProvider.func_223434_a(SourceFile:401) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.server.ServerChunkProvider$$Lambda$7825/1246145672.accept(Unknown Source) ~[?:?] {}
	at it.unimi.dsi.fastutil.longs.Long2ObjectLinkedOpenHashMap$1.forEach(Long2ObjectLinkedOpenHashMap.java:1661) ~[fastutil-8.2.1.jar:?] {}
	at com.google.common.collect.Iterables$UnmodifiableIterable.forEach(Iterables.java:105) ~[guava-21.0.jar:?] {}
	at net.minecraft.world.server.ServerChunkProvider.func_217220_m(SourceFile:366) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.server.ServerChunkProvider.func_217207_a(SourceFile:335) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:309) ~[?:?] {re:mixin,re:classloading,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:831) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:766) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:112) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:624) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51] {}
Caused by: java.lang.ClassNotFoundException: me.swirtzly.minecraft.angels.client.models.poses.PoseManager
	at java.lang.ClassLoader.findClass(ClassLoader.java:530) ~[?:1.8.0_51] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_51] {}
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:103) ~[modlauncher-4.1.0.jar:?] {re:classloading}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_51] {}
	... 24 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at me.swirtzly.minecraft.angels.common.entities.WeepingAngelEntity.func_70088_a(WeepingAngelEntity.java:87)
	at net.minecraft.entity.Entity.<init>(Entity.java:219)
	at net.minecraft.entity.LivingEntity.<init>(LivingEntity.java:192)
	at net.minecraft.entity.MobEntity.<init>(MobEntity.java:99)
	at net.minecraft.entity.CreatureEntity.<init>(SourceFile:12)
	at net.minecraft.entity.monster.MonsterEntity.<init>(SourceFile:26)
	at me.swirtzly.minecraft.angels.common.entities.QuantumLockBaseEntity.<init>(QuantumLockBaseEntity.java:31)
	at me.swirtzly.minecraft.angels.common.entities.WeepingAngelEntity.<init>(WeepingAngelEntity.java:65)
	at me.swirtzly.minecraft.angels.common.entities.WeepingAngelEntity.<init>(WeepingAngelEntity.java:61)
	at me.swirtzly.minecraft.angels.common.WAObjects$EntityEntries$$Lambda$4423/1766344207.create(Unknown Source)
	at net.minecraft.entity.EntityType.func_200721_a(EntityType.java:412)
	at net.minecraft.world.spawner.WorldEntitySpawner.func_222263_a(WorldEntitySpawner.java:113)
	at net.minecraft.world.server.ServerChunkProvider.func_223434_a(SourceFile:401)
	at net.minecraft.world.server.ServerChunkProvider$$Lambda$7825/1246145672.accept(Unknown Source)
	at it.unimi.dsi.fastutil.longs.Long2ObjectLinkedOpenHashMap$1.forEach(Long2ObjectLinkedOpenHashMap.java:1661)
	at com.google.common.collect.Iterables$UnmodifiableIterable.forEach(Iterables.java:105)
	at net.minecraft.world.server.ServerChunkProvider.func_217220_m(SourceFile:366)
	at net.minecraft.world.server.ServerChunkProvider.func_217207_a(SourceFile:335)
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:309)

-- Affected level --
Details:
	All players: 1 total; [ServerPlayerEntity['TheXeonMations'/261, l='New World', x=327.19, y=77.75, z=436.99]]
	Chunk stats: ServerChunkCache: 3550
	Level dimension: minecraft:overworld
	Level name: New World
	Level seed: -928031602166178524
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: {}
	Level spawn location: World: (64,64,160), Chunk: (at 0,4,0 in 4,10; contains blocks 64,0,160 to 79,255,175), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 126402 game time, 172817 day time
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 146183 (now: false), thunder time: 134853 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:831)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:766)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:112)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:624)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.14.4
	Minecraft Version ID: 1.14.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1754961488 bytes (1673 MB) / 4827643904 bytes (4604 MB) up to 7758938112 bytes (7399 MB)
	CPUs: 12
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx8323m -Xms256m -XX:PermSize=256m
	ModLauncher: 4.1.0+62+5bfa59b
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-1.0.0-service.jar eventbus PLUGINSERVICE 
		/forge-1.14.4-28.2.23.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.14.4-28.2.23.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-1.0.5-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.14.4-28.2.23.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.14.4-28.2.23.jar runtimedistcleaner PLUGINSERVICE 
		/forge-1.14.4-28.2.23.jar fml TRANSFORMATIONSERVICE 
		/MixinBootstrap-1.0.3.jar mixinbootstrap TRANSFORMATIONSERVICE 
		/MixinBootstrap-1.0.3.jar mixin PLUGINSERVICE 
		/MixinBootstrap-1.0.3.jar mixinbootstrap PLUGINSERVICE 
	FML: 28.2
	Forge: net.minecraftforge:28.2.23
	FML Language Providers: 
		javafml@28.2
		minecraft@1
	Mod List: 
		Notes-1.14.4-1.2.0.jar Notes {notes@1.14.4-1.2.0 DONE}
		torchslabmod-1.14.4_v1.5.jar Torch Slab Mod {torchslabmod@1.5 DONE}
		inventoryprofiles-forge-1.14.4-0.3.2.jar Inventory Profiles {inventoryprofiles@0.3.2 DONE}
		jei-1.14.4-6.0.0.29.jar Just Enough Items {jei@6.0.0.29 DONE}
		music_player-1.14.4-2.0.10.78.jar Music Player {musicplayer@2.0.10.78 DONE}
		rsgauges-1.14.4-1.2.4.jar Gauges and Switches {rsgauges@1.2.4 DONE}
		essentials-1.14.4-2.6.10.jar Essentials {essentials@1.14.4-2.6.10 DONE}
		create-mc1.14.4_v0.2.3.jar Create {create@mc1.14-0.2.3 DONE}
		journeymap-1.14.4-5.7.0b3.jar Journeymap {journeymap@5.7.0b3 DONE}
		ReAuth-1.14-1.15-3.8.1.jar ReAuth {reauth@3.8.1 DONE}
		essentialfeatures-3.0.1.jar Essential Features {essentialfeatures@3.0.1 DONE}
		citadel-1.0.4-1.14.4.jar Citadel {citadel@1.0.4 DONE}
		NaturesCompass-1.14.4-1.8.5.jar Nature's Compass {naturescompass@1.14.4-1.8.5 DONE}
		NetehrOverhaul1.14.4Ver1.7.jar NetherUpdate {netherupdate@1.0.0 DONE}
		Powah-1.14.4-0.2.8.jar Powah {powah@0.2.8 DONE}
		Fence Jumper-1.14.4-1.0.8.jar FenceJumper {fencejumper@version DONE}
		BetterAnimationsCollection2-v1.1b4-1.14.4.jar Better Animations Collection 2 {betteranimationscollection2@1.1b4 DONE}
		u_team_core-1.14.4-2.8.2.150.jar U Team Core {uteamcore@2.8.2.150 DONE}
		PickUpNotifier-v1.1.2-1.14.4.jar Pick Up Notifier {pickupnotifier@1.1.2 DONE}
		deathquotes-1.2-1.14.4.jar DeathQuotes {deathquotes@1.0 DONE}
		Hwyla-forge-1.10.6-B67_1.14.4.jar Waila {waila@version DONE}
		LetMeSleep-v1.2.1-1.14.4.jar Let Me Sleep {letmesleep@1.2.1 DONE}
		immersive-portals-0.15(for mc 1.14 with forge).jar Immersive Portals {immersive_portals@0.15 DONE}
		forge-1.14.4-28.2.23-universal.jar Forge {forge@28.2.23 DONE}
		shetiphiancore-1.14-3.6.2.jar ShetiPhian-Core {shetiphiancore@3.6.2 DONE}
		bettercompass-1.14.2-1.6.0.jar Better Compass {bettercompass@1.14.2-1.6.0 DONE}
		Tardis-Mod-1.14.4-1.3.1.jar TARDIS Mod {tardis@1.3.1 DONE}
		Regeneration-1.14.4-2.0.6.jar Regeneration {regeneration@2.0.6 DONE}
		Weeping-Angels-1.14-2.1.6.jar Weeping Angels {weeping_angels@2.1.6 DONE}
		absentbydesign-1.14.4-1.0.7.jar Absent By Design Mod {absentbydesign@1.14.4-1.0.7 DONE}
		refinedstorage-1.7.3.jar Refined Storage {refinedstorage@1.7.3 DONE}
		TheRCMod-v4.0.1.1 [1.14.4].jar The RC Mod {thercmod@4.0.1.1 DONE}
		colouredchat-1.14.4-1.4.6.jar ColouredChat {colouredchat@1.14.4-1.4.6 DONE}
		forge-1.14.4-28.2.23-client.jar Minecraft {minecraft@1.14.4 DONE}
		mcpaint-1.4.5.jar Mc Paint {mcpaint@1.4.5 DONE}
		Lollipop-1.14.4-0.0.23.jar Lollipop {lollipop@0.0.23 DONE}
		LetSleepingDogsLie-1.14.4-1.1.0.jar Let Sleeping Dogs Lie {dogslie@1.1.0 DONE}
		Futurepack-1.14.4-28.0.163.jar Futurepack {futurepack@28.0.163 DONE}
		Ding-1.14.4-1.1.0.jar Ding {ding@1.1.0 DONE}
		galaxysedge-1.14.4-1.0.2.jar Galaxy's Edge {galaxysedge@NONE DONE}
		rats-4.1.1-1.14.4.jar Rats {rats@4.1.1 DONE}
		gravestone-1.15.3.jar Gravestone Mod {gravestone@1.15.3 DONE}
		RandomThings-MC1.14.4-5.0.1.jar Random Things {randomthings@5.0.1 DONE}
		camera-1.4.10.jar Camera Mod {camera@1.4.10 DONE}
		multibeds-1.14-1.5.4.jar Multi-Beds {multibeds@1.5.4 DONE}
		[1.14.4] SecurityCraft v1.8.19.jar SecurityCraft {securitycraft@v1.8.19 DONE}
		OreExcavation-1.6.147.jar Ore Excavation {oreexcavation@NONE DONE}
		enderchests-1.14-1.5.3.jar EnderChests {enderchests@1.5.3 DONE}
		DoubleSlabs-1.14-1.7.6.jar Double Slabs {doubleslabs@1.7.6 DONE}
		elevatorid-1.14.4-1.5.2.jar Elevator Mod {elevatorid@1.14.4-1.5.2 DONE}
		AppleSkin-mc1.14.4-forge-1.0.14.jar AppleSkin {appleskin@1.0.14 DONE}
		engineersdecor-1.14.4-1.1.0.jar Engineer's Decor {engineersdecor@1.1.0 DONE}
		cc-tweaked-1.14.4-1.89.2.jar CC: Tweaked {computercraft@1.89.2 DONE}
		YAMDA-4.0.1.jar YAMDA {yamda@4.0.1 DONE}
		nametagswithoutanvil-1.1.jar Example Mod {nametagswithoutanvil@1.1 DONE}
		MineMenu-1.14.4-1.8.2.jar MineMenu {minemenu@1.14.4-1.8.2 DONE}
		CodeChickenLib-1.14.4-3.2.8.374-universal.jar CodeChicken Lib {codechickenlib@3.2.8.374 DONE}
		EnderStorage-1.14.4-2.4.8.144-universal.jar EnderStorage {enderstorage@2.4.8.144 DONE}
		thuttech-1.14.4-7.0.1.jar Thut Elevators {thuttech@7.0.1 DONE}
		thutcore-1.14.4-6.0.3.jar Thut Core {thutcore@6.0.3 DONE, thutcrafts@6.0.3 DONE}
	Player Count: 1 / 8; [ServerPlayerEntity['TheXeonMations'/261, l='New World', x=327.19, y=77.75, z=436.99]]
	Data Packs: vanilla, mod:absentbydesign, mod:appleskin, mod:betteranimationscollection2, mod:bettercompass, mod:camera, mod:citadel, mod:codechickenlib, mod:colouredchat, mod:computercraft, mod:create, mod:deathquotes, mod:ding, mod:dogslie, mod:doubleslabs, mod:elevatorid, mod:enderchests, mod:enderstorage, mod:engineersdecor, mod:essentialfeatures, mod:essentials, mod:fencejumper, mod:forge, mod:futurepack, mod:galaxysedge, mod:gravestone, mod:immersive_portals, mod:inventoryprofiles, mod:jei, mod:journeymap, mod:letmesleep, mod:lollipop, mod:mcpaint, mod:minemenu, mod:multibeds, mod:musicplayer, mod:nametagswithoutanvil, mod:naturescompass, mod:netherupdate, mod:notes, mod:oreexcavation, mod:pickupnotifier, mod:powah, mod:randomthings, mod:rats, mod:reauth, mod:refinedstorage, mod:regeneration (incompatible), mod:rsgauges, mod:securitycraft, mod:shetiphiancore, mod:tardis, mod:thercmod, mod:thutcore, mod:thuttech, mod:torchslabmod, mod:uteamcore, mod:waila, mod:weeping_angels, mod:yamda
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'

**Comment by Jeryn99** [comment]
You are running an outdated version.

Here is a link to the latest. 

https://www.curseforge.com/minecraft/mc-mods/weeping-angels-mod/files/2995765

If this issue still happens after, leave a comment here and I will re-open it.
