### ISSUE TITLE
1.15.2 - error during create_registries event phase.

### ISSUE THREAD

**Issue by Jusey1** [ReallySub/Weeping-Angels-Mod#127]
[11Sep2020 13:52:21.863] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher running: args [--username, Jusey1, --version, MultiMC5, --gameDir, C:/Users/Jusey/Documents/My Games/Minecraft/MultiMC/instances/Test/.minecraft, --assetsDir, C:/Users/Jusey/Documents/My Games/Minecraft/MultiMC/assets, --assetIndex, 1.15, --uuid, 5f311b1c855742cc9c333605ea8f524f, --accessToken, ????????, --userType, mojang, --versionType, release, --launchTarget, fmlclient, --fml.forgeVersion, 31.2.0, --fml.mcVersion, 1.15.2, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20200515.085601, --width, 854, --height, 480]
[11Sep2020 13:52:21.867] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher 5.1.0+69+master.79f13f7 starting: java version 1.8.0_261 by Oracle Corporation
[11Sep2020 13:52:22.498] [main/INFO] [net.minecraftforge.fml.loading.FixSSL/CORE]: Added Lets Encrypt root certificates as additional trust
[11Sep2020 13:52:22.542] [main/WARN] [net.minecraftforge.fml.loading.FMLConfig/CORE]: Configuration file C:\Users\Jusey\Documents\My Games\Minecraft\MultiMC\instances\Test\.minecraft\config\fml.toml is not correct. Correcting
[11Sep2020 13:52:22.549] [main/WARN] [net.minecraftforge.fml.loading.FMLConfig/CORE]: Incorrect key [defaultConfigPath] was corrected from null to defaultconfigs
[11Sep2020 13:52:23.953] [main/INFO] [cpw.mods.modlauncher.LaunchServiceHandler/MODLAUNCHER]: Launching target 'fmlclient' with arguments [--version, MultiMC5, --gameDir, C:\Users\Jusey\Documents\My Games\Minecraft\MultiMC\instances\Test\.minecraft, --assetsDir, C:\Users\Jusey\Documents\My Games\Minecraft\MultiMC\assets, --uuid, 5f311b1c855742cc9c333605ea8f524f, --username, Jusey1, --assetIndex, 1.15, --accessToken, ????????, --userType, mojang, --versionType, release, --width, 854, --height, 480]
[11Sep2020 13:52:25.861] [Render thread/INFO] [net.minecraft.client.Minecraft/]: Setting user: Jusey1
[11Sep2020 13:52:31.638] [Render thread/INFO] [net.minecraft.client.Minecraft/]: Backend library: LWJGL version 3.2.2 build 10
[11Sep2020 13:52:32.581] [modloading-worker-9/INFO] [net.minecraftforge.common.ForgeMod/FORGEMOD]: Forge mod loading, version 31.2.0, for MC 1.15.2 with MCP 20200515.085601
[11Sep2020 13:52:32.582] [modloading-worker-9/INFO] [net.minecraftforge.common.MinecraftForge/FORGE]: MinecraftForge v31.2.0 Initialized
[11Sep2020 13:52:32.818] [Render thread/ERROR] [net.minecraftforge.fml.javafmlmod.FMLModContainer/]: Exception caught during firing event: net.minecraftforge.registries.DeferredRegister.create(Lnet/minecraftforge/registries/IForgeRegistry;Ljava/lang/String;)Lnet/minecraftforge/registries/DeferredRegister;
	Index: 3
	Listeners:
		0: NORMAL
		1: ASM: class me.swirtzly.minecraft.angels.client.poses.AngelPoses onRegisterNewRegistries(Lnet/minecraftforge/event/RegistryEvent$NewRegistry;)V
		2: LOWEST
		3: ASM: me.swirtzly.minecraft.angels.WeepingAngels@2381d1e1 onNewRegistries(Lnet/minecraftforge/event/RegistryEvent$NewRegistry;)V
java.lang.NoSuchMethodError: net.minecraftforge.registries.DeferredRegister.create(Lnet/minecraftforge/registries/IForgeRegistry;Ljava/lang/String;)Lnet/minecraftforge/registries/DeferredRegister;
	at me.swirtzly.minecraft.angels.common.WAObjects$Sounds.<clinit>(WAObjects.java:136)
	at me.swirtzly.minecraft.angels.WeepingAngels.onNewRegistries(WeepingAngels.java:53)
	at net.minecraftforge.eventbus.ASMEventHandler_1_WeepingAngels_onNewRegistries_NewRegistry.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258)
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.fireEvent(FMLModContainer.java:106)
	at java.util.function.Consumer.lambda$andThen$0(Unknown Source)
	at java.util.function.Consumer.lambda$andThen$0(Unknown Source)
	at net.minecraftforge.fml.ModContainer.transitionState(ModContainer.java:112)
	at net.minecraftforge.fml.ModList.lambda$dispatchSynchronousEvent$5(ModList.java:126)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
	at java.util.stream.ReferencePipeline$Head.forEach(Unknown Source)
	at net.minecraftforge.fml.ModList.dispatchSynchronousEvent(ModList.java:126)
	at net.minecraftforge.fml.ModList.lambda$static$1(ModList.java:96)
	at net.minecraftforge.fml.LifecycleEventProvider.dispatch(LifecycleEventProvider.java:71)
	at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:214)
	at net.minecraftforge.fml.ModLoader.lambda$gatherAndInitializeMods$22(ModLoader.java:202)
	at net.minecraftforge.registries.GameData.fireCreateRegistryEvents(GameData.java:948)
	at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:202)
	at net.minecraftforge.fml.client.ClientModLoader.lambda$begin$2(ClientModLoader.java:97)
	at net.minecraftforge.fml.client.ClientModLoader.lambda$createRunnableWithCatch$5(ClientModLoader.java:113)
	at net.minecraftforge.fml.client.ClientModLoader.begin(ClientModLoader.java:97)
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:392)
	at net.minecraft.client.main.Main.main(SourceFile:166)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

[11Sep2020 13:52:32.821] [Render thread/ERROR] [net.minecraftforge.fml.javafmlmod.FMLModContainer/LOADING]: Caught exception during event RegistryEvent.NewRegistry dispatch for modid weeping_angels
java.lang.NoSuchMethodError: net.minecraftforge.registries.DeferredRegister.create(Lnet/minecraftforge/registries/IForgeRegistry;Ljava/lang/String;)Lnet/minecraftforge/registries/DeferredRegister;
	at me.swirtzly.minecraft.angels.common.WAObjects$Sounds.<clinit>(WAObjects.java:136) ~[?:1.0.1]
	at me.swirtzly.minecraft.angels.WeepingAngels.onNewRegistries(WeepingAngels.java:53) ~[?:1.0.1]
	at net.minecraftforge.eventbus.ASMEventHandler_1_WeepingAngels_onNewRegistries_NewRegistry.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80) ~[eventbus-2.2.0-service.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-2.2.0-service.jar:?]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.fireEvent(FMLModContainer.java:106) ~[?:31.2]
	at java.util.function.Consumer.lambda$andThen$0(Unknown Source) ~[?:1.8.0_261]
	at java.util.function.Consumer.lambda$andThen$0(Unknown Source) ~[?:1.8.0_261]
	at net.minecraftforge.fml.ModContainer.transitionState(ModContainer.java:112) ~[?:?]
	at net.minecraftforge.fml.ModList.lambda$dispatchSynchronousEvent$5(ModList.java:126) ~[?:?]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source) ~[?:1.8.0_261]
	at java.util.stream.ReferencePipeline$Head.forEach(Unknown Source) ~[?:1.8.0_261]
	at net.minecraftforge.fml.ModList.dispatchSynchronousEvent(ModList.java:126) ~[?:?]
	at net.minecraftforge.fml.ModList.lambda$static$1(ModList.java:96) ~[?:?]
	at net.minecraftforge.fml.LifecycleEventProvider.dispatch(LifecycleEventProvider.java:71) ~[?:?]
	at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:214) ~[?:?]
	at net.minecraftforge.fml.ModLoader.lambda$gatherAndInitializeMods$22(ModLoader.java:202) ~[?:?]
	at net.minecraftforge.registries.GameData.fireCreateRegistryEvents(GameData.java:948) ~[?:?]
	at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:202) ~[?:?]
	at net.minecraftforge.fml.client.ClientModLoader.lambda$begin$2(ClientModLoader.java:97) ~[?:?]
	at net.minecraftforge.fml.client.ClientModLoader.lambda$createRunnableWithCatch$5(ClientModLoader.java:113) ~[?:?]
	at net.minecraftforge.fml.client.ClientModLoader.begin(ClientModLoader.java:97) ~[?:?]
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:392) ~[?:?]
	at net.minecraft.client.main.Main.main(SourceFile:166) ~[minecraft-1.15.2-client.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_261]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_261]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_261]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_261]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56) ~[forge-1.15.2-31.2.0-launcher.jar:31.2]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-5.1.0.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-5.1.0.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-5.1.0.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-5.1.0.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-5.1.0.jar:?]
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:50) [ForgeWrapper-1.4.2.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_261]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_261]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_261]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_261]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
[11Sep2020 13:52:32.824] [Render thread/FATAL] [net.minecraftforge.fml.ModLoader/LOADING]: Failed to complete lifecycle event CREATE_REGISTRIES, 1 errors found
[11Sep2020 13:52:32.825] [Render thread/FATAL] [net.minecraftforge.eventbus.EventBus/EVENTBUS]: EventBus 0 shutting down - future events will not be posted.
java.lang.Exception: stacktrace
	at net.minecraftforge.eventbus.EventBus.shutdown(EventBus.java:278) ~[eventbus-2.2.0-service.jar:?]
	at net.minecraftforge.fml.client.ClientModLoader.lambda$createRunnableWithCatch$5(ClientModLoader.java:115) ~[?:?]
	at net.minecraftforge.fml.client.ClientModLoader.begin(ClientModLoader.java:97) ~[?:?]
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:392) ~[?:?]
	at net.minecraft.client.main.Main.main(SourceFile:166) ~[minecraft-1.15.2-client.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_261]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_261]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_261]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_261]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56) ~[forge-1.15.2-31.2.0-launcher.jar:31.2]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-5.1.0.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-5.1.0.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-5.1.0.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-5.1.0.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-5.1.0.jar:?]
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:50) [ForgeWrapper-1.4.2.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_261]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_261]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_261]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_261]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
[11Sep2020 13:52:34.022] [Render thread/INFO] [com.mojang.text2speech.NarratorWindows/]: Narrator library for x64 successfully loaded
[11Sep2020 13:52:34.116] [Render thread/INFO] [net.minecraft.resources.SimpleReloadableResourceManager/]: Reloading ResourceManager: Default, Mod Resources
[11Sep2020 13:52:34.148] [Server-Worker-7/WARN] [net.minecraftforge.common.ForgeConfigSpec/CORE]: Configuration file C:\Users\Jusey\Documents\My Games\Minecraft\MultiMC\instances\Test\.minecraft\config\forge-client.toml is not correct. Correcting
[11Sep2020 13:52:34.149] [Server-Worker-7/WARN] [net.minecraftforge.common.ForgeConfigSpec/CORE]: Incorrect key client was corrected from null to SimpleCommentedConfig:{}
[11Sep2020 13:52:34.150] [Server-Worker-7/WARN] [net.minecraftforge.common.ForgeConfigSpec/CORE]: Incorrect key client.zoomInMissingModelTextInGui was corrected from null to false
[11Sep2020 13:52:34.150] [Server-Worker-7/WARN] [net.minecraftforge.common.ForgeConfigSpec/CORE]: Incorrect key client.forgeCloudsEnabled was corrected from null to true
[11Sep2020 13:52:34.150] [Server-Worker-7/WARN] [net.minecraftforge.common.ForgeConfigSpec/CORE]: Incorrect key client.disableStairSlabCulling was corrected from null to false
[11Sep2020 13:52:34.150] [Server-Worker-7/WARN] [net.minecraftforge.common.ForgeConfigSpec/CORE]: Incorrect key client.alwaysSetupTerrainOffThread was corrected from null to false
[11Sep2020 13:52:34.150] [Server-Worker-7/WARN] [net.minecraftforge.common.ForgeConfigSpec/CORE]: Incorrect key client.forgeLightPipelineEnabled was corrected from null to true
[11Sep2020 13:52:34.151] [Server-Worker-7/WARN] [net.minecraftforge.common.ForgeConfigSpec/CORE]: Incorrect key client.experimentalForgeLightPipelineEnabled was corrected from null to false
[11Sep2020 13:52:34.151] [Server-Worker-7/WARN] [net.minecraftforge.common.ForgeConfigSpec/CORE]: Incorrect key client.selectiveResourceReloadEnabled was corrected from null to true
[11Sep2020 13:52:34.151] [Server-Worker-7/WARN] [net.minecraftforge.common.ForgeConfigSpec/CORE]: Incorrect key client.showLoadWarnings was corrected from null to true
[11Sep2020 13:52:34.156] [Server-Worker-7/WARN] [net.minecraftforge.common.ForgeConfigSpec/CORE]: Configuration file C:\Users\Jusey\Documents\My Games\Minecraft\MultiMC\instances\Test\.minecraft\config\weeping_angels-common.toml is not correct. Correcting
[11Sep2020 13:52:34.157] [Server-Worker-7/WARN] [net.minecraftforge.common.ForgeConfigSpec/CORE]: Incorrect key world_gen was corrected from null to SimpleCommentedConfig:{}
[11Sep2020 13:52:34.157] [Server-Worker-7/WARN] [net.minecraftforge.common.ForgeConfigSpec/CORE]: Incorrect key world_gen.arms was corrected from null to true
[11Sep2020 13:52:34.157] [Server-Worker-7/WARN] [net.minecraftforge.common.ForgeConfigSpec/CORE]: Incorrect key world_gen.genCatacombs was corrected from null to false
[11Sep2020 13:52:34.157] [Server-Worker-7/WARN] [net.minecraftforge.common.ForgeConfigSpec/CORE]: Incorrect key world_gen.chanceCatacombs was corrected from null to 25
[11Sep2020 13:52:34.158] [Server-Worker-7/WARN] [net.minecraftforge.common.ForgeConfigSpec/CORE]: Incorrect key world_gen.genOres was corrected from null to true
[11Sep2020 13:52:34.159] [Server-Worker-7/WARN] [net.minecraftforge.common.ForgeConfigSpec/CORE]: Incorrect key spawn was corrected from null to SimpleCommentedConfig:{}
[11Sep2020 13:52:34.159] [Server-Worker-7/WARN] [net.minecraftforge.common.ForgeConfigSpec/CORE]: Incorrect key spawn.minimumSpawn was corrected from null to 1
[11Sep2020 13:52:34.159] [Server-Worker-7/WARN] [net.minecraftforge.common.ForgeConfigSpec/CORE]: Incorrect key spawn.maximumSpawn was corrected from null to 1
[11Sep2020 13:52:34.159] [Server-Worker-7/WARN] [net.minecraftforge.common.ForgeConfigSpec/CORE]: Incorrect key spawn.spawnWeight was corrected from null to 5
[11Sep2020 13:52:34.159] [Server-Worker-7/WARN] [net.minecraftforge.common.ForgeConfigSpec/CORE]: Incorrect key spawn.spawnType was corrected from null to MONSTER
[11Sep2020 13:52:34.160] [Server-Worker-7/WARN] [net.minecraftforge.common.ForgeConfigSpec/CORE]: Incorrect key spawn.allowedBiomes was corrected from null to [minecraft:taiga_hills, minecraft:taiga, minecraft:desert, minecraft:desert_hills, minecraft:plains, minecraft:swamp, minecraft:beach, minecraft:snowy_taiga]
[11Sep2020 13:52:34.161] [Server-Worker-7/WARN] [net.minecraftforge.common.ForgeConfigSpec/CORE]: Incorrect key angel was corrected from null to SimpleCommentedConfig:{}
[11Sep2020 13:52:34.161] [Server-Worker-7/WARN] [net.minecraftforge.common.ForgeConfigSpec/CORE]: Incorrect key angel.hardcoreMode was corrected from null to false
[11Sep2020 13:52:34.161] [Server-Worker-7/WARN] [net.minecraftforge.common.ForgeConfigSpec/CORE]: Incorrect key angel.playScrapeSound was corrected from null to true
[11Sep2020 13:52:34.162] [Server-Worker-7/WARN] [net.minecraftforge.common.ForgeConfigSpec/CORE]: Incorrect key angel.playSeenSounds was corrected from null to true
[11Sep2020 13:52:34.162] [Server-Worker-7/WARN] [net.minecraftforge.common.ForgeConfigSpec/CORE]: Incorrect key angel.damage was corrected from null to 8.0
[11Sep2020 13:52:34.162] [Server-Worker-7/WARN] [net.minecraftforge.common.ForgeConfigSpec/CORE]: Incorrect key angel.xpGained was corrected from null to 25
[11Sep2020 13:52:34.162] [Server-Worker-7/WARN] [net.minecraftforge.common.ForgeConfigSpec/CORE]: Incorrect key angel.chickenGoboom was corrected from null to true
[11Sep2020 13:52:34.162] [Server-Worker-7/WARN] [net.minecraftforge.common.ForgeConfigSpec/CORE]: Incorrect key angel.torchBlowOut was corrected from null to true
[11Sep2020 13:52:34.163] [Server-Worker-7/WARN] [net.minecraftforge.common.ForgeConfigSpec/CORE]: Incorrect key angel.freezeOnAngel was corrected from null to false
[11Sep2020 13:52:34.163] [Server-Worker-7/WARN] [net.minecraftforge.common.ForgeConfigSpec/CORE]: Incorrect key angel.pickaxeOnly was corrected from null to true
[11Sep2020 13:52:34.163] [Server-Worker-7/WARN] [net.minecraftforge.common.ForgeConfigSpec/CORE]: Incorrect key angel.stalkRange was corrected from null to 65
[11Sep2020 13:52:34.163] [Server-Worker-7/WARN] [net.minecraftforge.common.ForgeConfigSpec/CORE]: Incorrect key angel.moveSpeed was corrected from null to 1.5
[11Sep2020 13:52:34.163] [Server-Worker-7/WARN] [net.minecraftforge.common.ForgeConfigSpec/CORE]: Incorrect key angel.blockBreaking was corrected from null to true
[11Sep2020 13:52:34.164] [Server-Worker-7/WARN] [net.minecraftforge.common.ForgeConfigSpec/CORE]: Incorrect key angel.disAllowedBlocks was corrected from null to [minecraft:magma_block, minecraft:glowstone, minecraft:sea_lantern, tardis:exterior_steampunk, tardis:exterior_clock, minecraft:air]
[11Sep2020 13:52:34.164] [Server-Worker-7/WARN] [net.minecraftforge.common.ForgeConfigSpec/CORE]: Incorrect key angel.blockBreakRange was corrected from null to 15
[11Sep2020 13:52:34.164] [Server-Worker-7/WARN] [net.minecraftforge.common.ForgeConfigSpec/CORE]: Incorrect key angel.transparentBlocks was corrected from null to []
[11Sep2020 13:52:34.166] [Server-Worker-7/WARN] [net.minecraftforge.common.ForgeConfigSpec/CORE]: Incorrect key teleport was corrected from null to SimpleCommentedConfig:{}
[11Sep2020 13:52:34.166] [Server-Worker-7/WARN] [net.minecraftforge.common.ForgeConfigSpec/CORE]: Incorrect key teleport.teleportType was corrected from null to RANDOM_PLACE
[11Sep2020 13:52:34.166] [Server-Worker-7/WARN] [net.minecraftforge.common.ForgeConfigSpec/CORE]: Incorrect key teleport.notAllowedDimensions was corrected from null to [DimensionType{minecraft:the_end}]
[11Sep2020 13:52:34.166] [Server-Worker-7/WARN] [net.minecraftforge.common.ForgeConfigSpec/CORE]: Incorrect key teleport.justTeleport was corrected from null to false
[11Sep2020 13:52:34.166] [Server-Worker-7/WARN] [net.minecraftforge.common.ForgeConfigSpec/CORE]: Incorrect key teleport.teleportRange was corrected from null to 450
[11Sep2020 13:52:34.167] [Server-Worker-7/WARN] [net.minecraftforge.common.ForgeConfigSpec/CORE]: Incorrect key teleport.angelDimTeleport was corrected from null to true
[11Sep2020 13:52:34.169] [Server-Worker-7/ERROR] [net.minecraftforge.fml.ModLoader/LOADING]: Skipping lifecycle event SETUP, 1 errors found.
[11Sep2020 13:52:34.170] [Server-Worker-7/FATAL] [net.minecraftforge.fml.ModLoader/LOADING]: Failed to complete lifecycle event SETUP, 1 errors found
[11Sep2020 13:52:34.170] [Server-Worker-7/FATAL] [net.minecraftforge.eventbus.EventBus/EVENTBUS]: EventBus 0 shutting down - future events will not be posted.
java.lang.Exception: stacktrace
	at net.minecraftforge.eventbus.EventBus.shutdown(EventBus.java:278) ~[eventbus-2.2.0-service.jar:?]
	at net.minecraftforge.fml.client.ClientModLoader.lambda$createRunnableWithCatch$5(ClientModLoader.java:115) ~[?:?]
	at net.minecraftforge.fml.client.ClientModLoader.startModLoading(ClientModLoader.java:123) ~[?:?]
	at net.minecraftforge.fml.client.ClientModLoader.lambda$onreload$3(ClientModLoader.java:105) ~[?:?]
	at net.minecraftforge.fml.client.ClientModLoader.lambda$createRunnableWithCatch$5(ClientModLoader.java:113) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) [?:1.8.0_261]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(Unknown Source) [?:1.8.0_261]
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) [?:1.8.0_261]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source) [?:1.8.0_261]
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) [?:1.8.0_261]
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) [?:1.8.0_261]
[11Sep2020 13:52:36.959] [Server-Worker-6/ERROR] [net.minecraftforge.fml.ModLoader/LOADING]: Skipping lifecycle event ENQUEUE_IMC, 1 errors found.
[11Sep2020 13:52:36.960] [Server-Worker-6/FATAL] [net.minecraftforge.fml.ModLoader/LOADING]: Failed to complete lifecycle event ENQUEUE_IMC, 1 errors found
[11Sep2020 13:52:36.960] [Server-Worker-6/FATAL] [net.minecraftforge.eventbus.EventBus/EVENTBUS]: EventBus 0 shutting down - future events will not be posted.
java.lang.Exception: stacktrace
	at net.minecraftforge.eventbus.EventBus.shutdown(EventBus.java:278) ~[eventbus-2.2.0-service.jar:?]
	at net.minecraftforge.fml.client.ClientModLoader.lambda$createRunnableWithCatch$5(ClientModLoader.java:115) ~[?:?]
	at net.minecraftforge.fml.client.ClientModLoader.finishModLoading(ClientModLoader.java:137) ~[?:?]
	at net.minecraftforge.fml.client.ClientModLoader.lambda$onreload$4(ClientModLoader.java:107) ~[?:?]
	at java.util.concurrent.CompletableFuture.uniRun(Unknown Source) [?:1.8.0_261]
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(Unknown Source) [?:1.8.0_261]
	at java.util.concurrent.CompletableFuture$Completion.exec(Unknown Source) [?:1.8.0_261]
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) [?:1.8.0_261]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source) [?:1.8.0_261]
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) [?:1.8.0_261]
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) [?:1.8.0_261]
[11Sep2020 13:52:37.843] [Render thread/INFO] [net.minecraft.client.audio.SoundSystem/]: OpenAL initialized.
[11Sep2020 13:52:37.844] [Render thread/INFO] [net.minecraft.client.audio.SoundEngine/SOUNDS]: Sound engine started
[11Sep2020 13:52:37.977] [Render thread/INFO] [net.minecraft.client.renderer.texture.AtlasTexture/]: Created: 1024x512x4 minecraft:textures/atlas/blocks.png-atlas
[11Sep2020 13:52:38.087] [Render thread/INFO] [net.minecraft.client.renderer.texture.AtlasTexture/]: Created: 128x128x4 minecraft:textures/atlas/signs.png-atlas
[11Sep2020 13:52:38.088] [Render thread/INFO] [net.minecraft.client.renderer.texture.AtlasTexture/]: Created: 512x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
[11Sep2020 13:52:38.092] [Render thread/INFO] [net.minecraft.client.renderer.texture.AtlasTexture/]: Created: 512x512x4 minecraft:textures/atlas/shield_patterns.png-atlas
[11Sep2020 13:52:38.095] [Render thread/INFO] [net.minecraft.client.renderer.texture.AtlasTexture/]: Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas
[11Sep2020 13:52:38.097] [Render thread/INFO] [net.minecraft.client.renderer.texture.AtlasTexture/]: Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
[11Sep2020 13:52:38.100] [Render thread/INFO] [net.minecraft.client.renderer.texture.AtlasTexture/]: Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
[11Sep2020 13:52:38.420] [Render thread/INFO] [net.minecraft.client.renderer.texture.AtlasTexture/]: Created: 256x256x0 minecraft:textures/atlas/particles.png-atlas
[11Sep2020 13:52:38.424] [Render thread/INFO] [net.minecraft.client.renderer.texture.AtlasTexture/]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
[11Sep2020 13:52:38.425] [Render thread/INFO] [net.minecraft.client.renderer.texture.AtlasTexture/]: Created: 128x128x0 minecraft:textures/atlas/mob_effects.png-atlas
[latest.log](https://github.com/WhoCraft/Weeping-Angels/files/5210797/latest.log)

**Comment by Jeryn99** [comment]
What is your forge version? Numbers, please don't say "latest"

**Comment by Jusey1** [comment]
Who tf will say "latest"? But anyways, Forge version is 31.2.0. I prefer to stick to the recommended version usually unless I have to use a different version for a specific mod. I also tested the mod on it's own, with nothing else installed but the Forge, and this is the log it gives me.

**Comment by Jeryn99** [comment]
Trust me, the amount of people who reply "latest" is quite high 

Anyways, I think you'll need to try a higher version, the mod uses deferred registries which was introduced in 1.15.2 at some point

If the issue is still there using latest, I will definitely have to look into this, but so far noone else has came forward with this

**Comment by Jusey1** [comment]
Yeah, you are correct. The mod properly works as intended. So the registries it uses just wasn't introduced in 31.2.0 which means the mod itself works just fine as long as you have the right Forge version (or higher). No worries though, some mods are already like this so I will eventually need to make a new forge server for myself and friends anyways.
