### ISSUE TITLE
1.16.4 Mod loading error has occured

### ISSUE THREAD

**Issue by North-West-Wind** [ReallySub/Weeping-Angels-Mod#135]
Using forge 1.16.4, 35.0.7

```---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 11/18/20 4:48 PM
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.fml.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:85) [?:?] {re:classloading}
	at net.minecraftforge.fml.client.ClientModLoader.completeModLoading(ClientModLoader.java:188) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.lambda$null$1(Minecraft.java:508) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:randompatches:RandomPatches Minecraft Transformer,pl:mixin:APP:kubejs.mixins.json:MinecraftMixin,pl:mixin:APP:shutupexperimentalsettings.mixins.json:client.MixinMinecraft,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft$$Lambda$24080/1088323565.run(Unknown Source) [?:?] {}
	at net.minecraft.util.Util.func_215077_a(SourceFile:404) [?:?] {re:classloading}
	at net.minecraft.client.Minecraft.lambda$new$2(Minecraft.java:504) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:randompatches:RandomPatches Minecraft Transformer,pl:mixin:APP:kubejs.mixins.json:MinecraftMixin,pl:mixin:APP:shutupexperimentalsettings.mixins.json:client.MixinMinecraft,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft$$Lambda$18265/958939134.accept(Unknown Source) [?:?] {}
	at net.minecraft.client.gui.ResourceLoadProgressGui.func_230430_a_(ResourceLoadProgressGui.java:113) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:allthetweaks.mixins.json:ProgressLoadGuiMixin,pl:mixin:APP:kubejs.mixins.json:ResourceLoadProgressGuiMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:480) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:976) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:randompatches:RandomPatches Minecraft Transformer,pl:mixin:APP:kubejs.mixins.json:MinecraftMixin,pl:mixin:APP:shutupexperimentalsettings.mixins.json:client.MixinMinecraft,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:randompatches:RandomPatches Minecraft Transformer,pl:mixin:APP:kubejs.mixins.json:MinecraftMixin,pl:mixin:APP:shutupexperimentalsettings.mixins.json:client.MixinMinecraft,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.4-35.0.7.jar:35.0] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$496/717151165.call(Unknown Source) [forge-1.16.4-35.0.7.jar:35.0] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.6.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.6.jar:?] {re:classloading}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.entity.MobEntity.<init>(MobEntity.java:109) ~[?:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMobEntity,pl:mixin:A}
-- MOD weeping_angels --
Details:
	Caused by 0: java.lang.ExceptionInInitializerError
		at me.swirtzly.minecraft.angels.utils.ClientUtil$$Lambda$23105/54493240.apply(Unknown Source) ~[?:?] {}
		at net.minecraftforge.fml.client.registry.ClientRegistry.bindTileEntityRenderer(ClientRegistry.java:49) ~[?:?] {re:classloading}
		at me.swirtzly.minecraft.angels.utils.ClientUtil.doClientStuff(ClientUtil.java:69) ~[?:1.0.5] {re:classloading}
		at me.swirtzly.minecraft.angels.WeepingAngels$$Lambda$23056/1162534827.run(Unknown Source) ~[?:?] {}
		at net.minecraftforge.fml.DistExecutor.unsafeRunWhenOn(DistExecutor.java:125) ~[?:?] {re:classloading}
		at net.minecraftforge.fml.DistExecutor.runWhenOn(DistExecutor.java:109) ~[?:?] {re:classloading}
		at me.swirtzly.minecraft.angels.WeepingAngels.doClientStuff(WeepingAngels.java:84) ~[?:1.0.5] {re:classloading}
		at me.swirtzly.minecraft.angels.WeepingAngels$$Lambda$6635/1822824302.accept(Unknown Source) ~[?:?] {}
		at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-3.0.5-service.jar:?] {}
		at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-3.0.5-service.jar:?] {}
		at net.minecraftforge.eventbus.EventBus$$Lambda$2952/1527597068.invoke(Unknown Source) ~[?:?] {}
		at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297) ~[eventbus-3.0.5-service.jar:?] {}
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:120) ~[?:35.0] {re:classloading}
		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:111) ~[?:?] {re:classloading}
		at net.minecraftforge.fml.ModContainer$$Lambda$3803/316982944.run(Unknown Source) ~[?:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1618) ~[?:1.8.0_51] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1610) ~[?:1.8.0_51] {}
		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_51] {}
		at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_51] {}
		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) ~[?:1.8.0_51] {}
		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_51] {}

	Mod File: Weeping-Angels-1.16.x-1.0.5.jar
	Failure message: Weeping Angels (weeping_angels) encountered an error during the sided_setup event phase
		java.lang.ExceptionInInitializerError: null
	Mod Version: 1.0.4
	Mod Issue URL: https://github.com/Swirtzly/Weeping-Angels/issues
	Exception message: java.lang.NullPointerException
Stacktrace:
	at net.minecraft.entity.MobEntity.<init>(MobEntity.java:109) ~[?:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMobEntity,pl:mixin:A}
	at net.minecraft.entity.CreatureEntity.<init>(SourceFile:12) ~[?:?] {re:mixin,re:classloading}
	at net.minecraft.entity.monster.MonsterEntity.<init>(SourceFile:30) ~[?:?] {re:mixin,re:classloading}
	at net.minecraft.entity.monster.AbstractSkeletonEntity.<init>(AbstractSkeletonEntity.java:64) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.entity.monster.SkeletonEntity.<init>(SourceFile:13) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at me.swirtzly.minecraft.angels.client.renders.tileentities.CoffinRenderer.<clinit>(CoffinRenderer.java:28) ~[?:1.0.5] {re:classloading}
	at me.swirtzly.minecraft.angels.utils.ClientUtil$$Lambda$23105/54493240.apply(Unknown Source) ~[?:?] {}
	at net.minecraftforge.fml.client.registry.ClientRegistry.bindTileEntityRenderer(ClientRegistry.java:49) ~[?:?] {re:classloading}
	at me.swirtzly.minecraft.angels.utils.ClientUtil.doClientStuff(ClientUtil.java:69) ~[?:1.0.5] {re:classloading}
	at me.swirtzly.minecraft.angels.WeepingAngels$$Lambda$23056/1162534827.run(Unknown Source) ~[?:?] {}
	at net.minecraftforge.fml.DistExecutor.unsafeRunWhenOn(DistExecutor.java:125) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.DistExecutor.runWhenOn(DistExecutor.java:109) ~[?:?] {re:classloading}
	at me.swirtzly.minecraft.angels.WeepingAngels.doClientStuff(WeepingAngels.java:84) ~[?:1.0.5] {re:classloading}
	at me.swirtzly.minecraft.angels.WeepingAngels$$Lambda$6635/1822824302.accept(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-3.0.5-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-3.0.5-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus$$Lambda$2952/1527597068.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297) ~[eventbus-3.0.5-service.jar:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:120) ~[?:35.0] {re:classloading}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:111) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModContainer$$Lambda$3803/316982944.run(Unknown Source) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1618) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1610) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_51] {}
```

**Comment by Jeryn99** [comment]
Serverside or client side?

**Comment by Jeryn99** [comment]
Nevermind, fixed it https://www.curseforge.com/minecraft/mc-mods/weeping-angels-mod/files/3115299

Check back at that link after 10 minutes

**Comment by North-West-Wind** [comment]
Thank you
