### ISSUE TITLE
The /kill command does not affect weeping angels.

### ISSUE THREAD

**Issue by Gotyam** [ReallySub/Weeping-Angels-Mod#143]
The /kill command does not affect weeping angels, both before and after "pickaxe only" damage has been toggled.
![image](https://user-images.githubusercontent.com/32512743/103214497-d7936e80-4910-11eb-85e7-39ef895d761b.png)

The overspawning (in another issue) is why I wish to kill them, but sadly I cannot.

Using version 1.0.7 for MC 1.16.4

**Comment by Gotyam** [comment]
I will say what I did to "fix" the issue. Obviously I have disabled the spawning of the angels, and to get rid of the ones that exist I used the TP command to get them all into a room full of chronodyne generators (aka angel kill room).

**Comment by Jeryn99** [comment]
The over spawning is strange, it's being looked into in #140 
I'll look into fixing the kill command, I thought I already had, but it seems that may have been in a previous Minecraft Version

**Comment by 50ap5ud5** [comment]
Thanks for reporting.

I can confirm this issue does persist in your version, 1.0.7. It's caused by the Angel's damage source checks not allowing the Angel to take the damage type used by the kill command. 

This has been fixed in commit 8b11dc6. I've made a test build that includes this patch. Would you mind testing this out and confirm the fix works?
https://www.mediafire.com/file/kjzrgrr8s24mrwz/Weeping-Angels-1.16.x-1.0.8-SPAWN-TEST.jar/file

**Comment by Gotyam** [comment]
Don't know if it was for me or swirtz to test that version, but I can say after 1 minute that the kill command does affect weeping angels now. In other news, the weeping angel spawn item lost its texture, and crashes the game when you try to place them.

Edit: The issue is more severe than I thought. The world crashes on being loaded. As i do not know how to do spoiler tags or anything to shorten the thing, here is the short part of the crash log. Will tweak with optifine to see if that is the cause.
Edit 2: Was not optifine, but this means I am out of ideas myself on getting it working again. Updated the error log to the one without optifine

Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at net.minecraft.client.renderer.entity.EntityRendererManager.func_229086_a_(EntityRendererManager.java:238) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.WorldRenderer.func_228426_a_(WorldRenderer.java:982) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:betterendforge.mixins.json:WorldRendererMixin,pl:mixin:APP:structure_gel.mixins.json:WorldRendererMixin,pl:mixin:APP:charm.mixins.json:WorldRendererMixin,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.WorldRendererAccess,pl:mixin:APP:immersiveengineering.mixins.json:coremods.client.WorldRendererMixin,pl:mixin:APP:nowplaying.mixins.json:WorldRendererMixin,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorWorldRenderer,pl:mixin:APP:assets/botania/botania.mixins.json:MixinWorldRenderer,pl:mixin:APP:imm_ptl_mixins.json:client.render.MixinWorldRenderer,pl:mixin:APP:imm_ptl_mixins.json:client.render.MixinWorldRenderer_Clouds,pl:mixin:APP:imm_ptl_peripheral_mixins.json:client.alternate_dimension.MixinWorldRenderer_A,pl:mixin:APP:imm_ptl_peripheral_mixins.json:client.altius_world.MixinWorldRenderer_A,pl:mixin:APP:imm_ptl_mixins.json:client.render.MixinWorldRenderer_Optional,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.func_228378_a_(GameRenderer.java:607) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:astralsorcery:reach_set_client_renderer,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.redirect$zpa000$redirectRenderingWorld(GameRenderer.java:1902) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:astralsorcery:reach_set_client_renderer,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:425) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:astralsorcery:reach_set_client_renderer,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:976) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:notenoughcreativity.mixins.json:MixinMinecraftClient,pl:mixin:APP:charm.mixins.json:accessor.MinecraftAccessor,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:nowplaying.mixins.json:MinecraftClientMixin,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMinecraft,pl:mixin:APP:imm_ptl_mixins.json:client.MixinMinecraftClient,pl:mixin:APP:imm_ptl_mixins.json:client.block_manipulation.MixinMinecraftClient_B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:notenoughcreativity.mixins.json:MixinMinecraftClient,pl:mixin:APP:charm.mixins.json:accessor.MinecraftAccessor,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:nowplaying.mixins.json:MinecraftClientMixin,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMinecraft,pl:mixin:APP:imm_ptl_mixins.json:client.MixinMinecraftClient,pl:mixin:APP:imm_ptl_mixins.json:client.block_manipulation.MixinMinecraftClient_B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.4-35.1.7.jar:35.1] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$487/1521891844.call(Unknown Source) [forge-1.16.4-35.1.7.jar:35.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.6.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.6.jar:?] {re:classloading}

Need probably up to a few hours to test the spawning issue, as I suspect the spawning itself could've been fine, but angels spawned in one place, went to another (chasing player), and then a new angel spawned where the first one did a bit later. Rinse and repeat until giant angel groups of lag galore.

**Comment by Jeryn99** [comment]
The issue appears to lie with Botania from a glance, they appear to be using Mixins on some rendering code which could cause this crash.

**Comment by Gotyam** [comment]
Just an update: The cause is not any of the following:
Optifine
Botania
Astral Sorcery
Charm
NotEnoughCreativity
BetterEnd
Immersive Engineering
Now Playing

Decided to make a custom pack quickly where I have weeping angel + the mods I saw in the crash report. Will try to slowly add more and see where the problem lies.

**Comment by Gotyam** [comment]
Alright, so I will just say I managed something I didn't expect to manage. I decided to, instead of adding mods, I would go from my full pack and reduce them (first get rid of mods starting with A, then B etc.). Got all the way down to literally no mods apart from Weeping Angels. Even went and deleted all config folders and any leftover files. And it still crashes. I know if you just make a new profile and install the weeping angels, nothing (bad) happens, so how I have managed this I do not know. Also made a fresh world for every launch.

Edit: Now even after making a fresh profile and redownloading the file (in the event the one I had somehow got corrupt) it will not work. TLDR: New version no work, at least not for me anymore.

Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at net.minecraft.client.renderer.entity.EntityRendererManager.func_229086_a_(EntityRendererManager.java:238) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.WorldRenderer.func_228426_a_(WorldRenderer.java:982) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.func_228378_a_(GameRenderer.java:607) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:425) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:976) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.4-35.1.7.jar:35.1] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$423/1293252487.call(Unknown Source) [forge-1.16.4-35.1.7.jar:35.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.6.jar:?] {}

**Comment by Gotyam** [comment]
Closing the issue as the /kill command *does* work now. If another user comes with issues regarding the rendering of the Angels, or you encounter it yourselves, then please do find a way to fix it. Until then I shall be on the sidelines.
