### ISSUE TITLE
Incompatibility w/ Danny's Expansion mod

### ISSUE THREAD

**Issue by GamerGaven** [ReallySub/Weeping-Angels-Mod#165]
Using latest versions of both mods causes game to crash upon loading a world.
Here is the crash log, hope it helps. :)

---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 6/10/21 8:53 PM
Description: Ticking memory connection

java.lang.ClassCastException: me.suff.mc.angels.conversion.AngelInfection cannot be cast to com.bottomtextdanny.dannys_expansion.core.capabilities.player.DannyEntityCap
	at com.bottomtextdanny.dannys_expansion.core.Util.EntityUtil.getDannyCap(EntityUtil.java:27) ~[?:1.0.9] {re:classloading}
	at com.bottomtextdanny.dannys_expansion.core.events.TickHandler.onLogin(TickHandler.java:166) ~[?:1.0.9] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_41_TickHandler_onLogin_LoadFromFile.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus$$Lambda$2587/1221691726.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.event.ForgeEventFactory.firePlayerLoadingEvent(ForgeEventFactory.java:333) ~[?:?] {re:classloading}
	at net.minecraft.world.storage.PlayerData.func_237336_b_(PlayerData.java:58) ~[?:?] {re:classloading}
	at net.minecraft.server.management.PlayerList.func_72380_a(PlayerList.java:294) ~[?:?] {re:classloading}
	at net.minecraft.server.management.PlayerList.func_72355_a(PlayerList.java:128) ~[?:?] {re:classloading}
	at net.minecraft.network.login.ServerLoginNetHandler.func_147326_c(ServerLoginNetHandler.java:118) ~[?:?] {re:classloading}
	at net.minecraft.network.login.ServerLoginNetHandler.func_73660_a(ServerLoginNetHandler.java:65) ~[?:?] {re:classloading}
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:222) ~[?:?] {re:classloading}
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:134) ~[?:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:865) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:78) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) [?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) [?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer$$Lambda$6063/273714086.run(Unknown Source) [?:?] {}
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 6186673424 bytes (5900 MB) / 8959033344 bytes (8544 MB) up to 17179869184 bytes (16384 MB)
	CPUs: 16
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx16G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 8.0.9+86+master.3cf110c
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.1.30.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.1.30.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.1.30.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.5-36.1.30.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.1.30.jar fml TRANSFORMATIONSERVICE 
	FML: 36.1
	Forge: net.minecraftforge:36.1.30
	FML Language Providers: 
		javafml@36.1
		minecraft@1
	Mod List: 
		forge-1.16.5-36.1.30-client.jar                   |Minecraft                     |minecraft                     |1.16.5              |DONE      |Manifest: NOSIGNATURE
		forge-1.16.5-36.1.30-universal.jar                |Forge                         |forge                         |36.1.30             |DONE      |Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		Weeping-Angels-1.16.x-2.0.9.jar                   |Weeping Angels                |weeping_angels                |2.0.9               |DONE      |Manifest: NOSIGNATURE
		[BETA]dannys_expansion1.16.5-1.0.9.1.jar          |Danny's Expansion             |dannys_expansion              |1.0.9               |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: d6904311-a9e2-4225-a962-e34d99423b47
	Player Count: 0 / 8; []
	Data Packs: vanilla, mod:forge, mod:weeping_angels (incompatible), mod:dannys_expansion
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'

**Comment by Jeryn99** [comment]
Interesting. I am not sure whether this is caused by my code or by their code
I will look into this more

**Comment by Jeryn99** [comment]
I've confirmed the issue lies with Danny's expansion
Angels has something called a Capability, this is used for storing data onto the player, Danny's expansion appears to be trying to get their own capability but isn't checking if it's theres and tries to do one of their operations on the angel capability, causing a crash


The way I determined that the issue lies with Danny's expansion is, after some research, this crash happens with other mods that have capabilities

I would report this issue to their issue tracker or on their discord
