### ISSUE TITLE
[1.16.5] Possible Pose-related crash in 2.1.6

### ISSUE THREAD

**Issue by smoothuk** [ReallySub/Weeping-Angels-Mod#193]
Randomly encountered this crash while running around the overworld at night.  Multiple attempts to reload into world resulted in the same crash until Weeping Angels was disabled.

---- Minecraft Crash Report ----
// Illegal dabbing detected \o\

Time: 22/10/21 06:53
Description: Unexpected error

java.lang.IllegalStateException: Pose stack not empty
	at net.minecraft.client.renderer.WorldRenderer.func_228423_a_(WorldRenderer.java:1193) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:enhancedcelestials.mixins.json:client.MixinWorldRenderer,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.WorldRenderer.func_228426_a_(WorldRenderer.java:1014) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:enhancedcelestials.mixins.json:client.MixinWorldRenderer,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.func_228378_a_(GameRenderer.java:608) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:425) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:976) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) ~[minecraft-1.16.5-client.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_291] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_291] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_291] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_291] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.5-36.2.0-launcher.jar:36.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_291] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_291] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_291] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_291] {}
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:52) [ForgeWrapper-1.5.1.jar:1.5.1] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_291] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_291] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_291] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_291] {}
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?] {}
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?] {}
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?] {}
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.client.renderer.WorldRenderer.func_228423_a_(WorldRenderer.java:1193) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:enhancedcelestials.mixins.json:client.MixinWorldRenderer,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.WorldRenderer.func_228426_a_(WorldRenderer.java:1014) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:enhancedcelestials.mixins.json:client.MixinWorldRenderer,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.func_228378_a_(GameRenderer.java:608) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['SmoothOne'/142, l='ClientLevel', x=411.29, y=70.00, z=-465.01]]
	Chunk stats: Client Chunk Cache: 625, 249
	Level dimension: minecraft:overworld
	Level spawn location: World: (192,64,-208), Chunk: (at 0,4,0 in 12,-13; contains blocks 192,0,-208 to 207,255,-193), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 781895 game time, 1024062 day time
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:447) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:architectury.mixins.json:MixinClientLevel,pl:mixin:APP:enhancedcelestials.mixins.json:client.MixinClientWorld,pl:mixin:APP:mixins.sndctrl.json:MixinClientWorld,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2029) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:628) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) ~[minecraft-1.16.5-client.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_291] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_291] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_291] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_291] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.5-36.2.0-launcher.jar:36.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_291] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_291] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_291] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_291] {}
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:52) [ForgeWrapper-1.5.1.jar:1.5.1] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_291] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_291] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_291] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_291] {}
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?] {}
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?] {}
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?] {}
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?] {}

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_291, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3546179056 bytes (3381 MB) / 4199546880 bytes (4005 MB) up to 4199546880 bytes (4005 MB)
	CPUs: 4
	JVM Flags: 5 total; -XX:+UseParallelGC -XX:+AggressiveOpts -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms4096m -Xmx4096m
	ModLauncher: 8.0.9+86+master.3cf110c
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.2.0-launcher.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.0-launcher.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.2.0-launcher.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.0-launcher.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.2.0-launcher.jar fml TRANSFORMATIONSERVICE 
	FML: 36.2
	Forge: net.minecraftforge:36.2.0
	FML Language Providers: 
		javafml@36.2
		minecraft@1
	Mod List: 
		forge-1.16.5-36.2.0-client.jar                    |Minecraft                     |minecraft                     |1.16.5              |DONE      |Manifest: NOSIGNATURE
		Weeping-Angels-1.16.x-2.1.6.jar                   |Weeping Angels                |weeping_angels                |2.1.6               |DONE      |Manifest: NOSIGNATURE
		spiders-2.0-1.16.4-1.0.4 (1).jar                  |Spiders 2.0                   |spiderstpo                    |1.0.4               |DONE      |Manifest: NOSIGNATURE
		CreativeCore_v2.0.10_mc1.16.4 (1).jar             |CreativeCore                  |creativecore                  |2.0.0               |DONE      |Manifest: NOSIGNATURE
		jei-1.16.5-7.7.1.121.jar                          |Just Enough Items             |jei                           |7.7.1.121           |DONE      |Manifest: NOSIGNATURE
		The_Graveyard_1.0_(FORGE)_for_1.16.4-1.16.5.jar   |The Graveyard (FORGE)         |graveyard                     |1.0                 |DONE      |Manifest: NOSIGNATURE
		spookarms-1.0.0.8.jar                             |Spooky Arms                   |spookyarms                    |1.0.0.8             |DONE      |Manifest: NOSIGNATURE
		hostilevillages-3.1-1.16.5.jar                    |Example Mod                   |hostilevillages               |3.1-1.16.5          |DONE      |Manifest: NOSIGNATURE
		whisperwoods-1.16.5-2.0.2.jar                     |Whisperwoods                  |whisperwoods                  |2.0.2               |DONE      |Manifest: NOSIGNATURE
		gravestone-1.16.5-1.0.4.jar                       |Gravestone Mod                |gravestone                    |1.16.5-1.0.4        |DONE      |Manifest: NOSIGNATURE
		immortuoscalyx-1.16.5-1.5.2.jar                   |Immortuos Calyx               |immortuoscalyx                |1.16.5-1.5.2        |DONE      |Manifest: NOSIGNATURE
		specialai-1.16.5-1.0.0.jar                        |Special AI                    |specialai                     |1.16.5-1.0.0        |DONE      |Manifest: NOSIGNATURE
		EnhancedVisuals_v1.3.23_mc1.16.5.jar              |EnhancedVisuals               |enhancedvisuals               |1.3.0               |DONE      |Manifest: NOSIGNATURE
		froglins-1.16.4-1.0.1.5.jar                       |Froglins                      |froglins                      |1.16.4-1.0.1.5      |DONE      |Manifest: NOSIGNATURE
		infinitemusic-1.3.0.jar                           |Infinite Music                |infinitemusic                 |1.3.0               |DONE      |Manifest: NOSIGNATURE
		Undercover+Witches+1.0.1.jar                      |Undercover Witches            |undercoverwitches             |1.0.1               |DONE      |Manifest: NOSIGNATURE
		architectury-1.23.33-forge.jar                    |Architectury                  |architectury                  |1.23.33             |DONE      |Manifest: NOSIGNATURE
		ftb-library-forge-1605.3.3-build.71.jar           |FTB Library                   |ftblibrary                    |1605.3.3-build.71   |DONE      |Manifest: NOSIGNATURE
		outvoted-1.16.5-1.2.4.jar                         |Outvoted                      |outvoted                      |1.2.4               |DONE      |Manifest: NOSIGNATURE
		enhancedcelestials-2.0.8-1.16.5.jar               |Enhanced Celestials           |enhancedcelestials            |2.0.8-1.16.5        |DONE      |Manifest: NOSIGNATURE
		Ambience-1.16.4-1.0.1.jar                         |Ambience - Extras             |ambience                      |1.16.4-1.0.1        |DONE      |Manifest: NOSIGNATURE
		forge-1.16.5-36.2.0-universal.jar                 |Forge                         |forge                         |36.2.0              |DONE      |Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		AdvancedCompas-forge-1.16.5-1.2.5.jar             |Advanced Compass              |advancedcompass               |1.2.5               |DONE      |Manifest: NOSIGNATURE
		stalkercreepers-1.16.3.2.jar                      |Finder Compass                |stalkercreepers               |1.16.3.2            |DONE      |Manifest: NOSIGNATURE
		SoundFilters-0.14_for_1.16.2.jar                  |Sound Filters                 |soundfilters                  |0.14_for_1.16.2     |DONE      |Manifest: NOSIGNATURE
		geckolib-forge-1.16.5-3.0.46.jar                  |GeckoLib                      |geckolib3                     |3.0.46              |DONE      |Manifest: NOSIGNATURE
		OpenLoader-1.16.5-9.0.1.jar                       |OpenLoader                    |openloader                    |9.0.1               |DONE      |Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		DynamicSurroundings-1.16.4-4.0.4.2.jar            |ยง3Dynamic Surroundings        |dsurround                     |1.16.4-4.0.4.2      |DONE      |Manifest: b4:98:14:b9:76:55:25:4f:e5:5f:4d:71:90:87:43:5b:f9:d5:3a:02:60:42:5e:da:1f:15:9c:ff:be:a9:7c:77
	Crash Report UUID: e1e9715e-6219-43cd-9822-2f1d1ca89b08
	Launched Version: MultiMC5
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce GTX 1060 6GB/PCIe/SSE2 GL version 4.6.0 NVIDIA 461.72, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, mod_resources, file/Skyrim Soundpack v5.7.zip (incompatible), file/Tissou's+Zombie+Pack+1.16.zip, file/[1.16.5]CarefullyCamouflagedCreepers.zip, file/Custom Mob Textures
	Current Language: English (US)
	CPU: 4x Intel(R) Core(TM) i5-2500K CPU @ 3.30GHz

**Comment by Jeryn99** [comment]
Not sure the issue lays with angels, as the crash report mentions mixins that I did not create, such as ``MixinWorldRenderer``, these seem to come from something called enhancedcelestials?
Try without that mod and get back to me

**Comment by Jeryn99** [comment]
Any update?

**Comment by smoothuk** [comment]
Sorry about the late response.. kinda forgot about this.  Trying to reproduce the crash without enhancedcelestials, so far so good.  Will let you know soon as it explodes again.
