### ISSUE TITLE
Ticking Entity Crash

### ISSUE THREAD

**Issue by Kenzie-Young** [ReallySub/Weeping-Angels-Mod#287]
Below is a portion of my crash report. If you need more, please let me know.

----------------------------------------------------------------------------------------------------------------------------------
Time: 6/2/23 8:48 PM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at net.minecraft.server.management.PlayerList.transferPlayerToDimension(PlayerList.java:620)
	at net.minecraft.entity.player.EntityPlayerMP.changeDimension(EntityPlayerMP.java:695)
	at me.swirtzly.angels.utils.Teleporter.moveSafeAcrossDim(Teleporter.java:57)
	at me.swirtzly.angels.common.entities.EntityWeepingAngel.teleportInteraction(EntityWeepingAngel.java:432)
	at me.swirtzly.angels.common.entities.EntityWeepingAngel.func_70652_k(EntityWeepingAngel.java:154)
	at me.swirtzly.angels.common.entities.EntityQuantumLockBase.func_70636_d(EntityQuantumLockBase.java:72)
	at me.swirtzly.angels.common.entities.EntityWeepingAngel.func_70636_d(EntityWeepingAngel.java:237)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2179)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295)
	at net.minecraft.entity.monster.EntityMob.func_70071_h_(EntityMob.java:50)
	at me.swirtzly.angels.common.entities.EntityWeepingAngel.func_70071_h_(EntityWeepingAngel.java:312)
	at net.minecraft.world.World.func_72866_a(World.java:1996)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1958)
	at net.minecraft.world.World.func_72939_s(World.java:1762)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

(MixinBooter) Mixins in Stacktrace:
	net.minecraft.entity.EntityLiving:
		dev.satyrn.wolfarmor.mixin.MixinEntityLiving (mixins.wolfarmor.core.json)
		dev.satyrn.wolfarmor.mixin.accessors.EntityLivingAccessor (mixins.wolfarmor.core.json)
	net.minecraft.world.WorldServer:
		stevekung.mods.stevekunglib.mixin.WorldServerMixin (mixins.stevekung's_lib.json)
	net.minecraft.entity.EntityLivingBase:
		dev.satyrn.wolfarmor.mixin.MixinEntityLivingBase (mixins.wolfarmor.core.json)
		stevekung.mods.moreplanets.core.mixin.MixinEntityLivingBase (mixins.more_planets.json)
	net.minecraft.world.World:
		stevekung.mods.stevekunglib.mixin.WorldMixin (mixins.stevekung's_lib.json)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.server.management.PlayerList.transferPlayerToDimension(PlayerList.java:620)
	at net.minecraft.entity.player.EntityPlayerMP.changeDimension(EntityPlayerMP.java:695)
	at me.swirtzly.angels.utils.Teleporter.moveSafeAcrossDim(Teleporter.java:57)
	at me.swirtzly.angels.common.entities.EntityWeepingAngel.teleportInteraction(EntityWeepingAngel.java:432)
	at me.swirtzly.angels.common.entities.EntityWeepingAngel.func_70652_k(EntityWeepingAngel.java:154)
	at me.swirtzly.angels.common.entities.EntityQuantumLockBase.func_70636_d(EntityQuantumLockBase.java:72)
	at me.swirtzly.angels.common.entities.EntityWeepingAngel.func_70636_d(EntityWeepingAngel.java:237)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2179)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295)
	at net.minecraft.entity.monster.EntityMob.func_70071_h_(EntityMob.java:50)
	at me.swirtzly.angels.common.entities.EntityWeepingAngel.func_70071_h_(EntityWeepingAngel.java:312)
	at net.minecraft.world.World.func_72866_a(World.java:1996)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1958)

-- Entity being ticked --
Details:
	Entity Type: weeping-angels:weepingangel (me.swirtzly.angels.common.entities.EntityWeepingAngel)
	Entity ID: 9405
	Entity Name: Weeping Angel
	Entity's Exact location: -252.45, 73.00, 65.51
	Entity's Block location: World: (-253,73,65), Chunk: (at 3,4,1 in -16,4; contains blocks -256,0,64 to -241,255,79), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Entity's Momentum: 0.17, -0.05, 0.38
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1762)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)

**Comment by Kenzie-Young** [comment]
[crash-2023-06-02_20.48.21-server.txt](https://github.com/Suff99/Weeping-Angels/files/11640131/crash-2023-06-02_20.48.21-server.txt)

**Comment by Jeryn99** [comment]
1.12 is unsupported
