### ISSUE TITLE
crash when angels are attacked by non living sources

### ISSUE THREAD

**Issue by Efimero** [ReallySub/Weeping-Angels-Mod#3]
I don't know if this is directly your fault or just a lack of inter-mod compat shenanigans, but here's what happens:
```
Time: 4/4/18 9:30 AM
Description: Ticking entity

java.lang.ClassCastException: net.minecraft.entity.projectile.EntityLargeFireball cannot be cast to net.minecraft.entity.EntityLivingBase
	at com.github.reallysub.angels.common.entities.EntityAngel.cancelDamage(EntityAngel.java:318)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_333_EntityAngel_cancelDamage_LivingAttackEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.common.ForgeHooks.onLivingAttack(ForgeHooks.java:561)
	at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:848)
	at net.minecraft.entity.passive.EntityAnimal.func_70097_a(SourceFile:66)
	at net.minecraft.entity.projectile.EntityLargeFireball.func_70227_a(SourceFile:31)
	at net.minecraft.entity.projectile.EntityFireball.func_70071_h_(EntityFireball.java:98)
	at net.minecraft.world.World.func_72866_a(World.java:1990)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:831)
	at net.minecraft.world.World.func_72870_g(World.java:1952)
	at net.minecraft.world.World.func_72939_s(World.java:1756)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:612)
```
this happens with any damage source that is not EntitiyLiving even though you do check for the instanceof it
it happens with arrows and fireballs, and I assume it will happen with eggs, snowballs, primalcore stones etc etc etc
and the error is on the line with the cast, so the if check is passing when it shouldn't *shrug*
you need a better check and I don't know why ;w; <3

**Comment by Efimero** [comment]
oh, I see, you just fixed it and didn't upload the new build, oops

**Comment by ReallySub** [comment]
Hahaha, I'll get it onto curseforge soon <3 @Efimero
