### ISSUE TITLE
neo-forge: 21.0.87 and minecraft: 1.21 on server: NoSuchMethodError

### ISSUE THREAD

**Issue by koshnarek** [ReallySub/Weeping-Angels-Mod#366]
Playing locally runs fine... but on the server:

22Jul2024 11:25:53.377] [modloading-worker-0/ERROR] [net.neoforged.fml.javafmlmod.FMLModContainer/LOADING]: Failed to create mod instance. ModID: weeping_angels, class mc.craig.software.angels.neoforge.WeepingAngelsForge
java.lang.NoSuchMethodError: 'void mc.craig.software.angels.network.WANetworkManager.registerS2C(net.minecraft.network.protocol.common.custom.CustomPacketPayload$Type, net.minecraft.network.codec.StreamCodec, mc.craig.software.angels.network.WANetworkManager$Handler)'
	at TRANSFORMER/weeping_angels@1/mc.craig.software.angels.network.WANetworkManager.init(WANetworkManager.java:27) ~[forge-weeping_angels-mc1.21-v1.0.0-forge.jar%23243!/:?]
	at TRANSFORMER/weeping_angels@1/mc.craig.software.angels.WeepingAngels.init(WeepingAngels.java:45) ~[forge-weeping_angels-mc1.21-v1.0.0-forge.jar%23243!/:?]
	at TRANSFORMER/weeping_angels@1/mc.craig.software.angels.neoforge.WeepingAngelsForge.<init>(WeepingAngelsForge.java:40) ~[forge-weeping_angels-mc1.21-v1.0.0-forge.jar%23243!/:?]
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62) ~[?:?]
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502) ~[?:?]
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486) ~[?:?]
	at MC-BOOTSTRAP/fml_loader@4.0.18/net.neoforged.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:115) ~[loader-4.0.18.jar%2360!/:4.0]
	at MC-BOOTSTRAP/fml_loader@4.0.18/net.neoforged.fml.ModLoader.lambda$constructMods$3(ModLoader.java:153) ~[loader-4.0.18.jar%2360!/:4.0]
	at MC-BOOTSTRAP/fml_loader@4.0.18/net.neoforged.fml.ModLoader.lambda$dispatchParallelTask$7(ModLoader.java:231) ~[loader-4.0.18.jar%2360!/:4.0]
	at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:934) [?:?]
	at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:911) [?:?]
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483) [?:?]
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) [?:?]
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312) [?:?]
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843) [?:?]
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808) [?:?]
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188) [?:?]

minecraft: 1.21
neo-forge: 21.0.87

I`ll try to update neoforge (and maybe some of the 92 mods)

**Comment by Jeryn99** [comment]
Hello.

This is definitely a issue with my code, always good to have day one issues [🙄](https://emojipedia.org/face-with-rolling-eyes)

Looking into it

**Comment by Jeryn99** [comment]
Fixed: https://github.com/Jeryn99/Weeping-Angels/commit/9afdd69c60400ab84317f5c8c4f49570d862d0d3

Please download 1.0.2
